display_errors=On
error_reporting=E_ALL
upload_max_filesize=20M
post_max_size=20M
memory_limit=512M
max_execution_time=60
date.timezone=Europe/Paris

; Configuration encodage UTF-8
default_charset=UTF-8
mbstring.internal_encoding=UTF-8
mbstring.http_output=UTF-8
mbstring.encoding_translation=On
